name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        uses: docker/login-action@v2
      - name: Build and push Docker image
        run: |
          docker login --username neumont-victorkeeler --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build -t ghcr.io/neumont-victorkeeler/shenyun:latest .      
          docker push ghcr.io/neumont-victorkeeler/shenyun:latest
